%%
n=1;
m=1;
for i=1:length(ElemNOD(:,1))
xp=NODDDOW(i,1)*10^-3;
yp=NODDDOW(i,2)*10^-3;
zp=NODDDOW(i,3)*10^-3;
for j=1:length(ElemNOD(:,1))
%
xa=NODDOPL(j,1)*10^-3;
ya=NODDOPL(j,2)*10^-3;
za=NODDOPL(j,3)*10^-3;
xb=NODDOPP(j,1)*10^-3;
yb=NODDOPP(j,2)*10^-3;
zb=NODDOPP(j,3)*10^-3;
%
xt=(yp-ya)*(zp-zb)-(zp-za)*(yp-yb);
yt=-(xp-xa)*(zp-zb)+(zp-za)*(xp-xb);
zt=(xp-xa)*(yp-yb)-(yp-ya)*(xp-xb);
t=(xt)^2+(yt)^2+(zt)^2;
%
a=sqrt((xp-xa)^2+(yp-ya)^2+(zp-za)^2);
b=sqrt((xp-xb)^2+(yp-yb)^2+(zp-zb)^2);
%
dot1=(xb-xa)*(xp-xa)+(yb-ya)*(yp-ya)+(zb-za)*(zp-za);
dot2=(xb-xa)*(xp-xb)+(yb-ya)*(yp-yb)+(zb-za)*(zp-zb);
%
K=(1/(4*pi*t))*(dot1/a-dot2/b);
if t==0
u=0;
v=0;
z=0;
else
%
u=K*xt;
v=K*yt;
w=K*zt;
end
%
aij=u*NormalP(i,1)+v*NormalP(i,2)+w*NormalP(i,3);
As_Q(n,m)=aij;
m=m+1;
end
m=1;
n=n+1;
end
n=1;
m=1;
for i=1:length(ElemNOD(:,1))
xp=NODDDOW(i,1)*10^-3;
yp=NODDDOW(i,2)*10^-3;
zp=NODDDOW(i,3)*10^-3;
for j=1:length(ElemNOD(:,1))
%
xa=100000000000;
ya=NODDOPL(j,2)*10^-3;
za=NODDOPL(j,3)*10^-3;
xb=NODDOPL(j,1)*10^-3;
yb=NODDOPL(j,2)*10^-3;
zb=NODDOPL(j,3)*10^-3;
%
xt=(yp-ya)*(zp-zb)-(zp-za)*(yp-yb);
yt=-(xp-xa)*(zp-zb)+(zp-za)*(xp-xb);
zt=(xp-xa)*(yp-yb)-(yp-ya)*(xp-xb);
t=xt^2+yt^2+zt^2;
%
a=sqrt((xp-xa)^2+(yp-ya)^2+(zp-za)^2);
b=sqrt((xp-xb)^2+(yp-yb)^2+(zp-zb)^2);
%
dot1=(xb-xa)*(xp-xa)+(yb-ya)*(yp-ya)+(zb-za)*(zp-za);
dot2=(xb-xa)*(xp-xb)+(yb-ya)*(yp-yb)+(zb-za)*(zp-zb);
%
K=(1/(4*pi*t))*(dot1/a-dot2/b);
%
u=K*xt;
v=K*yt;
w=K*zt;
%
aij=u*NormalP(i,1)+v*NormalP(i,2)+w*NormalP(i,3);
As_L(n,m)=aij;
m=m+1;
end
m=1;
n=n+1;
end
k=1;
n=1;
m=1;
for i=1:length(ElemNOD(:,1))
xp=NODDDOW(i,1)*10^-3;
yp=NODDDOW(i,2)*10^-3;
zp=NODDDOW(i,3)*10^-3;
for j=1:length(ElemNOD(:,1))
%
xa=NODDOPP(j,1)*10^-3;
ya=NODDOPP(j,2)*10^-3;
za=NODDOPP(j,3)*10^-3;
xb=100000000000;
yb=NODDOPP(j,2)*10^-3;
zb=NODDOPP(j,3)*10^-3;
%
xt=(yp-ya)*(zp-zb)-(zp-za)*(yp-yb);
yt=-(xp-xa)*(zp-zb)+(zp-za)*(xp-xb);
zt=(xp-xa)*(yp-yb)-(yp-ya)*(xp-xb);
t=xt^2+yt^2+zt^2;
%
a=sqrt((xp-xa)^2+(yp-ya)^2+(zp-za)^2);
b=sqrt((xp-xb)^2+(yp-yb)^2+(zp-zb)^2);
%
dot1=(xb-xa)*(xp-xa)+(yb-ya)*(yp-ya)+(zb-za)*(zp-za);
dot2=(xb-xa)*(xp-xb)+(yb-ya)*(yp-yb)+(zb-za)*(zp-zb);
%
K=(1/(4*pi*t))*(dot1/a-dot2/b);
%
u=K*xt;
v=K*yt;
w=K*zt;
%
aij=u*NormalP(i,1)+v*NormalP(i,2)+w*NormalP(i,3);
As_R(n,m)=aij;
m=m+1;
end
m=1;
n=n+1;
end
for i=1:length(As_R)
for j=1:length(As_R)
a_lift=As_L(i,j)+As_R(i,j)+As_Q(i,j);
As(i,j)=a_lift;
end
end
n=1;
m=1;
for i=1:length(NODDDOW_dop(:,1))
xp=NODDDOW_dop(i,1)*10^-3;
yp=NODDDOW_dop(i,2)*10^-3;
zp=NODDDOW_dop(i,3)*10^-3;
for j=1:length(ElemNOD(:,1))
%
xb=NODDOPP(j,1)*10^-3;
yb=NODDOPP(j,2)*10^-3;
zb=NODDOPP(j,3)*10^-3;
xa=NODDOPL(j,1)*10^-3;
ya=NODDOPL(j,2)*10^-3;
za=NODDOPL(j,3)*10^-3;
%
xt=(yp-ya)*(zp-zb)-(zp-za)*(yp-yb);
yt=-(xp-xa)*(zp-zb)+(zp-za)*(xp-xb);
zt=(xp-xa)*(yp-yb)-(yp-ya)*(xp-xb);
t=xt^2+yt^2+zt^2;
%
a=sqrt((xp-xa)^2+(yp-ya)^2+(zp-za)^2);
b=sqrt((xp-xb)^2+(yp-yb)^2+(zp-zb)^2);
%
dot1=(xb-xa)*(xp-xa)+(yb-ya)*(yp-ya)+(zb-za)*(zp-za);
dot2=(xb-xa)*(xp-xb)+(yb-ya)*(yp-yb)+(zb-za)*(zp-zb);
%
K=(1/(4*pi*t))*(dot1/a-dot2/b);
%
u=K*xt;
v=K*yt;
w=K*zt;
%
bij=u*NormalP(i,1)+v*NormalP(i,2)+w*NormalP(i,3);
As_Q_drag(n,m)=bij;
m=m+1;
end
m=1;
n=n+1;
end
n=1;
m=1;
for i=1:length(NODDDOW_dop(:,1))
xp=NODDDOW_dop(i,1)*10^-3;
yp=NODDDOW_dop(i,2)*10^-3;
zp=NODDDOW_dop(i,3)*10^-3;
for j=1:length(ElemNOD(:,1))
%
xa=100000000000;
ya=NODDOPL(j,2)*10^-3;
za=NODDOPL(j,3)*10^-3;
xb=NODDOPL(j,1)*10^-3;
yb=NODDOPL(j,2)*10^-3;
zb=NODDOPL(j,3)*10^-3;
%
xt=(yp-ya)*(zp-zb)-(zp-za)*(yp-yb);
yt=-(xp-xa)*(zp-zb)+(zp-za)*(xp-xb);
zt=(xp-xa)*(yp-yb)-(yp-ya)*(xp-xb);
t=xt^2+yt^2+zt^2;
%
a=sqrt((xp-xa)^2+(yp-ya)^2+(zp-za)^2);
b=sqrt((xp-xb)^2+(yp-yb)^2+(zp-zb)^2);
%
dot1=(xb-xa)*(xp-xa)+(yb-ya)*(yp-ya)+(zb-za)*(zp-za);
dot2=(xb-xa)*(xp-xb)+(yb-ya)*(yp-yb)+(zb-za)*(zp-zb);
%
K=(1/(4*pi*t))*(dot1/a-dot2/b);
%
u=K*xt;
v=K*yt;
w=K*zt;
%
bij=u*NormalP(i,1)+v*NormalP(i,2)+w*NormalP(i,3);
As_L_drag(n,m)=bij;
m=m+1;
end
m=1;
n=n+1;
end
k=1;
n=1;
m=1;
for i=1:length(NODDDOW_dop(:,1))
xp=NODDDOW_dop(i,1)*10^-3;
yp=NODDDOW_dop(i,2)*10^-3;
zp=NODDDOW_dop(i,3)*10^-3;
for j=1:length(ElemNOD(:,1))
%
xa=NODDOPP(j,1)*10^-3;
ya=NODDOPP(j,2)*10^-3;
za=NODDOPP(j,3)*10^-3;
xb=100000000000;
yb=NODDOPP(j,2)*10^-3;
zb=NODDOPP(j,3)*10^-3;
%
xt=(yp-ya)*(zp-zb)-(zp-za)*(yp-yb);
yt=-(xp-xa)*(zp-zb)+(zp-za)*(xp-xb);
zt=(xp-xa)*(yp-yb)-(yp-ya)*(xp-xb);
t=xt^2+yt^2+zt^2;
%
a=sqrt((xp-xa)^2+(yp-ya)^2+(zp-za)^2);
b=sqrt((xp-xb)^2+(yp-yb)^2+(zp-zb)^2);
%
dot1=(xb-xa)*(xp-xa)+(yb-ya)*(yp-ya)+(zb-za)*(zp-za);
dot2=(xb-xa)*(xp-xb)+(yb-ya)*(yp-yb)+(zb-za)*(zp-zb);
%
K=(1/(4*pi*t))*(dot1/a-dot2/b);
%
u=K*xt;
v=K*yt;
w=K*zt;
%
bij=u*NormalP(i,1)+v*NormalP(i,2)+w*NormalP(i,3);
As_R_drag(n,m)=bij;
m=m+1;
end
m=1;
n=n+1;
end
for i=1:length(As_R_drag(:,1))
for j=1:length(As_R_drag)
a_drag=As_L_drag(i,j)+As_R_drag(i,j)+As_Q_drag(i,j);
As_drag(i,j)=a_drag;
end
end
clear Vel_vector t K u v w xp yp zp xa ya za xb yb zb xt yt zt a_drag aij bij a_lift a_drag n m i j As_R As_Q As_L As_R_drag As_L_drag As_Q_drag